trigger:
- main

pool:
  default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm install'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar-cloud'
    organization: 'malidisuryareddy'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: $(projectKey)
    cliProjectName: $(projectName)
    cliSources: '.'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm run build'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'SonarCloud'
